spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mental_health_db
    username: postgres
    password: Whitedevil411@
  data:
    redis:
      host: localhost
      port: 6379
      password: Whitedevil411@
  mail:
    host: smtp.gmail.com
    port: 587
    username: prajwalimmadi103@gmail.com
    password: dcnoqeqpuwqjbmsp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8081

app:
  jwt:
    secret: wLr7eRk1Dk29uL9YhYd0s2vVxTzR3cM8NfK1pQ7aBcX9Lm
    access-token-expiry: 900000
    refresh-token-expiry: 604800000
    issuer: cimhans-dev
  encryption:
    secret-key: 1234567890ABCDEF
  frontend-url: http://localhost:5173

logging:
  level:
    com.cimhans: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.authentication: TRACE
    org.flywaydb: INFO
